//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.02.23 at 05:10:51 PM CET
//


package ch.unifr.marcovr.GraphTransformer.gxl;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="graph"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "graph"
})
@XmlRootElement(name = "gxl")
public class GxlRoot {

    @XmlElement(required = true)
    private Graph graph;

    /**
     * Gets the value of the graph property.
     *
     * @return
     *     possible object is
     *     {@link Graph }
     *
     */
    public Graph getGraph() {
        return graph;
    }

    /**
     * Sets the value of the graph property.
     *
     * @param value
     *     allowed object is
     *     {@link Graph }
     *
     */
    public void setGraph(Graph value) {
        this.graph = value;
    }

}
